changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Deployment
      labels:
        - deployment
        - infra
    - title: Tests
      labels:
        - test
        - tests
    - title: Docs
      labels:
        - documentation
        - docs
    - title: Chores
      labels:
        - chore
        - maintenance
        - dependencies
    - title: Other Changes
      labels:
        - "*"
